Added libs regression

diff --git a/regress b/regress
--- a/regress
+++ b/regress
@@ -27,6 +27,21 @@ if [ $err -ne 0 ] ; then
     exit $err
 fi
 echo "regression SUCCESS"
+echo "checking libs"
+if [ `uname` = 'Darwin' ] ; then
+    otool -L target/bin/ffmpeg | awk '{print $1}' | sort | grep -v ffmpeg: | tee test.libs
+    ref=osx_ref.libs
+else
+    ldd target/binffmpeg | awk '{print $1}' | sort | tee test.libs
+    ref=linux_ref.libs
+fi
+diff -q $ref test.libs
+err=$?
+if [ $err -ne 0 ] ; then
+    echo "libs FAIL: `diff $ref test.libs`"
+    exit $err
+fi
+echo "libs SUCCESS"
 if [ $noass != '0' ] ; then
     exit 0
 fi
